Traceback (most recent call last):
  File "/home/adry/final/csc376_final/client1/../ChatClient.py", line 306, in <module>
    main()
  File "/home/adry/final/csc376_final/client1/../ChatClient.py", line 300, in main
    client(port, address, connect_server_port)
  File "/home/adry/final/csc376_final/client1/../ChatClient.py", line 175, in client
    sock.connect((address, connect_server_port)) 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/adry/final/csc376_final/client1/../ChatClient.py", line 306, in <module>
    main()
  File "/home/adry/final/csc376_final/client1/../ChatClient.py", line 300, in main
    client(port, address, connect_server_port)
  File "/home/adry/final/csc376_final/client1/../ChatClient.py", line 175, in client
    sock.connect((address, connect_server_port)) 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/adry/final/csc376_final/client1/../ChatClient.py", line 306, in <module>
    main()
  File "/home/adry/final/csc376_final/client1/../ChatClient.py", line 300, in main
    client(port, address, connect_server_port)
  File "/home/adry/final/csc376_final/client1/../ChatClient.py", line 175, in client
    sock.connect((address, connect_server_port)) 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionRefusedError: [Errno 111] Connection refused
