Traceback (most recent call last):
  File "/home/adry/final/csc376_final/client1/../ChatClient.py", line 349, in <module>
    main()
  File "/home/adry/final/csc376_final/client1/../ChatClient.py", line 343, in main
    client(port, address, connect_server_port)
  File "/home/adry/final/csc376_final/client1/../ChatClient.py", line 222, in client
    ui(sock, port, "client") 
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adry/final/csc376_final/client1/../ChatClient.py", line 277, in ui
    f_server(sock, port, filename) 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adry/final/csc376_final/client1/../ChatClient.py", line 67, in f_server
    serversocket.bind(('localhost', port)) 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/adry/final/csc376_final/client1/../ChatClient.py", line 349, in <module>
    main()
  File "/home/adry/final/csc376_final/client1/../ChatClient.py", line 343, in main
    client(port, address, connect_server_port)
  File "/home/adry/final/csc376_final/client1/../ChatClient.py", line 222, in client
    ui(sock, port, "client") 
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adry/final/csc376_final/client1/../ChatClient.py", line 277, in ui
    f_server(sock, port, filename) 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adry/final/csc376_final/client1/../ChatClient.py", line 67, in f_server
    serversocket.bind(('localhost', port)) 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 98] Address already in use
