Exception in thread Thread-1 (receive):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/adry/final/csc376_final/client3/../ChatClient.py", line 95, in receive
    port_recv = decode_recv(sock)
                ^^^^^^^^^^^^^^^^^
  File "/home/adry/final/csc376_final/client3/../ChatClient.py", line 84, in decode_recv
    msg_bytes = sock.recv(1024).decode()
                ^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/home/adry/final/csc376_final/client3/../ChatClient.py", line 285, in <module>
    main()
  File "/home/adry/final/csc376_final/client3/../ChatClient.py", line 279, in main
    client(port, address, connect_server_port)
  File "/home/adry/final/csc376_final/client3/../ChatClient.py", line 167, in client
    ui(sock, port, "client") 
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adry/final/csc376_final/client3/../ChatClient.py", line 213, in ui
    f_server(sock, port, filename) 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adry/final/csc376_final/client3/../ChatClient.py", line 74, in f_server
    sock.send(f_name.encode()) # PrimFTP_text.py code
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
